# Generated by Django 4.2.3 on 2023-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listing_actual_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.auction_listing'),
        ),
    ]
