# Generated by Django 4.2.3 on 2023-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0002_alter_category_description_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
