# Generated by Django 4.2.3 on 2023-09-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0003_alter_item_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemets',
            name='TransactionRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='item_track.transactionrecord'),
        ),
    ]
