# Generated by Django 4.2.3 on 2023-09-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0007_alter_client_address_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemets',
            name='observation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
