# Generated by Django 4.2.3 on 2023-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0008_movemets_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codebar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
