# Generated by Django 4.2.3 on 2023-09-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0009_item_codebar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='codebar',
            new_name='barcode',
        ),
    ]
