# Generated by Django 4.2.3 on 2023-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0010_rename_codebar_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
