# Generated by Django 4.2.3 on 2023-09-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_track', '0011_item_stock_min'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movemets',
            new_name='Movements',
        ),
    ]
